param:
  string: 'foo'
  integer: 1234
  float: 1234.5
  boolean: true
  list: [1.0, mixed list]
  dictionary: {a: b, c: d}
  test_one:
    type: a/b
    num: 1
  test_two:
    type: c/d
    num: 2
    array: {e: 3,f: 4,g: 5}
